

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."archiveBoard" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "writeNumber" bigint NOT NULL,
    "source" "text",
    "url" "text",
    "createdAt" timestamp with time zone,
    "mainTitle" "text",
    "subTitle" "text",
    "pay" "text",
    "schedule" "text",
    "isSubstitude" boolean,
    "isPlayedOnce" boolean
);


ALTER TABLE "public"."archiveBoard" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."locale" (
    "archiveBoardId" "uuid" NOT NULL,
    "sd" "text" DEFAULT 'NULL'::"text",
    "sgg" "text" DEFAULT 'NULL'::"text",
    "id" integer NOT NULL
);


ALTER TABLE "public"."locale" OWNER TO "postgres";


ALTER TABLE "public"."locale" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."locale_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."major" (
    "archiveBoardId" "uuid" NOT NULL,
    "category" "text" DEFAULT 'NULL'::"text",
    "id" integer NOT NULL,
    "majorName" "text" DEFAULT 'NULL'::"text"
);


ALTER TABLE "public"."major" OWNER TO "postgres";


ALTER TABLE "public"."major" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."major_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."archiveBoard"
    ADD CONSTRAINT "achive_board_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."locale"
    ADD CONSTRAINT "locale_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."locale"
    ADD CONSTRAINT "locale_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."major"
    ADD CONSTRAINT "major_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."major"
    ADD CONSTRAINT "major_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."locale"
    ADD CONSTRAINT "locale_archive_board_id_fkey" FOREIGN KEY ("archiveBoardId") REFERENCES "public"."archiveBoard"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."major"
    ADD CONSTRAINT "major_archiveBoardId_fkey" FOREIGN KEY ("archiveBoardId") REFERENCES "public"."archiveBoard"("id") ON DELETE CASCADE;



CREATE POLICY "Enable insert for anon users" ON "public"."archiveBoard" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Enable insert for anon users" ON "public"."locale" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Enable insert for anon users" ON "public"."major" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "Public profiles are insert to everyone." ON "public"."archiveBoard" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Public profiles are select to everyone." ON "public"."locale" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Public profiles are select to everyone." ON "public"."major" FOR SELECT TO "anon" USING (true);



CREATE POLICY "Public profiles are visible to everyone." ON "public"."archiveBoard" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."archiveBoard" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."locale" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."major" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


























































































































































































GRANT ALL ON TABLE "public"."archiveBoard" TO "anon";
GRANT ALL ON TABLE "public"."archiveBoard" TO "authenticated";
GRANT ALL ON TABLE "public"."archiveBoard" TO "service_role";



GRANT ALL ON TABLE "public"."locale" TO "anon";
GRANT ALL ON TABLE "public"."locale" TO "authenticated";
GRANT ALL ON TABLE "public"."locale" TO "service_role";



GRANT ALL ON SEQUENCE "public"."locale_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."locale_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."locale_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."major" TO "anon";
GRANT ALL ON TABLE "public"."major" TO "authenticated";
GRANT ALL ON TABLE "public"."major" TO "service_role";



GRANT ALL ON SEQUENCE "public"."major_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."major_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."major_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
